matrix:
  include:
    - language: node_js
      node_js:
        - "8"
      dist: bionic
      install:
        - ./install.sh
        - cd nodejs; npm install ; cd -
      script:
        - cd nodejs; node test.js


