name: docker test

on:
  push:

jobs:

  nodejs:
    defaults:
      run:
        working-directory: nodejs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Docker in rootless mode.
      uses: ScribeMD/rootless-docker@main
    - run: npm i
    - run: npm test
