name: docker test

on:
  push:
  workflow_dispatch:
jobs:

  nodejs:
    defaults:
      run:
        working-directory: nodejs
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@main
    - uses: davidkhala/setup-dockerode@main
    - run: npm i
    - run: npm test
  

  