name: docker test

on:
  push:

jobs:

  nodejs:
    defaults:
      run:
        working-directory: nodejs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Use Docker in rootless mode.
      uses: ScribeMD/rootless-docker@main
    - run: npm i
    - run: npm test
  runner:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl --unix-socket /var/run/docker.sock http://localhost/_ping
      - run: curl https://raw.githubusercontent.com/davidkhala/linux-utils/main/apps/docker/daemon.sh | bash -s expose
      - run: curl http://localhost:2375/_ping
