name: tests

on:
  push:

jobs:

  nodejs:
    defaults:
      run:
        working-directory: nodejs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm i
    - run: npm test
