name: docker test

on:
  push:

jobs:

  nodejs:
    defaults:
      run:
        working-directory: nodejs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
          sudo setenforce 0
          sudo systemctl disable --now docker
          dockerd-rootless-setuptool.sh install
          docker context use rootless
    - run: npm i
    - run: npm test
