name: docker test

on:
  push:

jobs:

  nodejs:
    defaults:
      run:
        working-directory: nodejs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Use Docker in rootless mode.
      uses: ScribeMD/rootless-docker@main
    - run: npm i
    - run: npm test
  runner:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl --unix-socket /var/run/docker.sock http://localhost/_ping
      - run: sudo curl https://raw.githubusercontent.com/davidkhala/linux-utils/main/apps/docker/docker.conf --create-dirs -o /etc/systemd/system/docker.service.d/docker.conf
      - run: cat /etc/docker/daemon.json |  jq '.hosts=["unix:///var/run/docker.sock","tcp://127.0.0.1:2375", "tcp://0.0.0.0:2376"]' | sudo tee /etc/docker/daemon.json
      - run: sudo systemctl daemon-reload
      - run: sudo systemctl restart docker
      - run: docker -H tcp://127.0.0.1:2375 ps
      - run: curl http://localhost:2375/_ping